rvm:
- 2.5.8
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
git:
  depth: false
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: RC/SGe76X0bePdUfFvZN9Eb76Lxd8eOGC6gHctKlEh9x2ve1LuBjRBirzrYMSRhCJox7erRpndMNkNgoh18DxghdO0VtZJabTF+XfYJoEzJTQFTX/Moe1Zx/zApwaXn/C0WdvfLKLdQN0miKhTtM4w9PbnRNq6clzP/M3qTD3aM=

  # Cloudflare purge
  - CLOUDFLARE_EMAIL: chris@cmbuckley.co.uk
  - secure: "M+RaMtpG+51bH06G/8ya73agWNbBDy8eX7CJZra4S8m3u2WRrilmY9TyLlUJNi/pz4oVe7thG7tbcaKiHTHWP+UXeDky2k+NScDawhu/h7kRqf2nrbNOs4g/iwnBdSviV4FMmgKvpS3Egh/KUuvqmL3MylINJlc4jBq8JTOvrwQ="
branches:
  only:
  - master
