rvm:
- 2.5.8
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: RC/SGe76X0bePdUfFvZN9Eb76Lxd8eOGC6gHctKlEh9x2ve1LuBjRBirzrYMSRhCJox7erRpndMNkNgoh18DxghdO0VtZJabTF+XfYJoEzJTQFTX/Moe1Zx/zApwaXn/C0WdvfLKLdQN0miKhTtM4w9PbnRNq6clzP/M3qTD3aM=

  # Cloudflare purge
  - CLOUDFLARE_EMAIL: chris@cmbuckley.co.uk
  - secure: R11ffXEQ3XV4M7lGu9yTv2j0fslR5Vs9EdRlP9OaBkxz2pe7VqcHI68f8PDaUwuse0YmnLsLRoZqTlSwYsxn8cKkiC9FdsDUXG/E1WfBe4s78+LXgSk62ToUqs1C8esxu6uIkX5QrXCVJGQm6mNRUQme9cnwaxOMxol9IGVuWNk=
branches:
  only:
  - master
