rvm:
- 2.5.8
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
git:
  depth: false
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: TehGtKGERrjy4ZAlDIkjo6MjLynbb+THO3fLmskYtMoEs5kCaTr4rszY8Bb6Sc+MvLk6gVG6IvqlKiCvb8Ef455j3ZLaNZimMpgJPAmWbm0VtqobVBK/E9vIcmTH+FPJLBZkoi9meywUkWsCZu93HucbDZF4NyYkdcse/SQTc80=

  # Cloudflare purge
  - CLOUDFLARE_EMAIL: chris@cmbuckley.co.uk
  - secure: "M+RaMtpG+51bH06G/8ya73agWNbBDy8eX7CJZra4S8m3u2WRrilmY9TyLlUJNi/pz4oVe7thG7tbcaKiHTHWP+UXeDky2k+NScDawhu/h7kRqf2nrbNOs4g/iwnBdSviV4FMmgKvpS3Egh/KUuvqmL3MylINJlc4jBq8JTOvrwQ="
branches:
  only:
  - master
