rvm:
- 2.5.8
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
git:
  depth: false
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.com
  - secure: TehGtKGERrjy4ZAlDIkjo6MjLynbb+THO3fLmskYtMoEs5kCaTr4rszY8Bb6Sc+MvLk6gVG6IvqlKiCvb8Ef455j3ZLaNZimMpgJPAmWbm0VtqobVBK/E9vIcmTH+FPJLBZkoi9meywUkWsCZu93HucbDZF4NyYkdcse/SQTc80=

  # Cloudflare purge
  - secure: "UrnJ09DWs3lrYd6+5MAcZRIdIE+oFLsQ4507TEhrzXvK68nWtq1TDLKAvVcFr2wQbJjcGjyjaGfqgB/poanGHzupBKmu95/R8SiavN2NuAMKdG7Qx2vtkp26jhY3doCP/9/hxWHxXVzgHwTOf7m1REPfLhIR2TfhUYutR8FKd7Q="
branches:
  only:
  - master
