rvm:
- 2.5.8
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: FzhqDehWCQmSdMRwg8K2mChj/+BD/3VFqxzirluQGvctImQpsv3WivoDGebq25c8ini1mfez2gCpm4DoBCIe0IdU+o9G25tu5znxqyviBLEQgB0m0SfDy9GQiJ3QF/OJQMRDlbBfCcr2jVYE4gF7tTG0QaDUFSZzbkFHf5m2mfQ=

  # Cloudflare purge
  - CLOUDFLARE_EMAIL: chris@cmbuckley.co.uk
  - secure: R11ffXEQ3XV4M7lGu9yTv2j0fslR5Vs9EdRlP9OaBkxz2pe7VqcHI68f8PDaUwuse0YmnLsLRoZqTlSwYsxn8cKkiC9FdsDUXG/E1WfBe4s78+LXgSk62ToUqs1C8esxu6uIkX5QrXCVJGQm6mNRUQme9cnwaxOMxol9IGVuWNk=
branches:
  only:
  - master
