before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-base

script: make travis

env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: cjEKuQoNia4MKtJeH3hyrmj3vQIuXsR8rWU9AQhclEcInMCj066qGCaepKNXlAPmdqTzSd+YBwdR1siXOpW7viywK8AlFRxbFlaZsWj6iN8DW+5pvdkQwrvni7mwUO6OCWxI4Uw60EVtPW2rOuwffH5A4tzNioZiytNL1rdfgqo=

branches:
  only:
  - master
