before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-base

script: make travis

env:
  - secure: "bVJZo4Xsg3jhcdVKc57ktY4zWYfnZFRtVNbdkkN6kT29V2C9gHBPb8LsfUBkX+7Li34yG2G9lhTcpmJWz0VdHSPN444+fhUb5TWbYcN4oqpgI4xST2LnFbsLg5mPOvZhy2eF5mtPi8ipkQBdb93InOlVHct5TeC+QLLVRoEHkKA="

branches:
  only:
    - master
