title: Chris Buckley
description: Chris Buckley's personal Web site
host: 0.0.0.0

url: https://cmbuckley.co.uk
baseurl: "/cv"

repository: cmbuckley/cv
remote_theme: "cmbuckley/cmbuckley.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

defaults:
  - scope:
      path: assets
    values:
      exclude: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

social:
   keybase:   cmbuckley
   hackerone: cmbuckley
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
