title: Chris Buckley
description: Chris Buckley's personal Web site
host: 0.0.0.0

url: https://cmbuckley.co.uk
baseurl: "/cv"

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /
 - title: CV
   url: /cv/
 - title: Contact
   url: /contact/
 - title: Blog
   url: /blog/
 - title: Interests
   url: /interests/
 - title: Projects
   url: /projects/

social:
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
   google:    https://bux.re/+
