name: Build CV
on:
  push:
    branches: master
jobs:
  build_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Install LaTeX packages
        run: sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra
      - name: Build assets
        run: make
      - name: Commit assets
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          git add -f cv.pdf index.md
          git commit -am "Updated GitHub Pages"
          git push -f origin HEAD:gh-pages
